INSTNAME: sly20100511212501
CACHING_STRATEGY: "BabelCache_Blackhole"
DATABASE:
  DRIVER: mysql
  HOST: localhost
  LOGIN: sally
  PASSWORD: ''
  NAME: sally_base
  PERSISTENT: false
  TABLE_PREFIX: sly_
babelcache:
  memcached: [localhost, 11211]
